### ISSUE TITLE
Uncaught TypeError: e.reframe is not a function

### ISSUE THREAD

**Issue by mohandere** [dollarshaveclub/reframe.js#12]
Hi 

There is an issue with $ shorthand function.

`window.$` is undefined in my case, instead `window.jQuery` works for me.

To fix this issue i did changed plugin code from,

    if (window.$) {
         window.$.fn.extend({
           reframe: function reframeFunc(cName) {
             return reframe(this, cName);
          }
      });
    }

To

    if (window.jQuery) {
         window.jQuery.fn.extend({
           reframe: function reframeFunc(cName) {
             return reframe(this, cName);
          }
      });
    }

**Comment by yowainwright** [comment]
Why not just use, `reframe(el)` & use plain javascript.

**Comment by mohandere** [comment]
Its not handy to write javascript selector so prefer jQuery way.

**Comment by yowainwright** [comment]
@mohandere you can write the selector the same way b/c the javascript using `document.querySelectorAll`. https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

**Comment by yowainwright** [comment]
@mohandere thanks again for your notes & time. V0.3.2 should work better for the use case you pointed out. 👌

**Comment by yowainwright** [comment]
@mohandere good catch on the `zepto` vs `Zepto`. I'm going to update that soon - next day or so. ~THANKS 🙏
