### ISSUE TITLE
Script breaks when width and height attributes are not set

### ISSUE THREAD

**Issue by Jakob-Maudience** [dollarshaveclub/reframe.js#177]
## The issue
The reframe script breaks with the error `Uncaught TypeError: Cannot read property 'indexOf' of null` if no size attributes are found on the frame element.

## Requested Update
Either implement a check to see if the frame has intrinsic size, and then use attributes as a fallback, or update documentation to clarify that these attributes are required.

As a workaround for now, I simply loop through the frames before and add the necessary attributes before I call reframe.

## Why Is This Update Needed?
I'm using this script on a site that uses a cms (wordpress), and I can't assume every iframe/embed code will have the required size attributes.

## Are There Examples Of This Requested Update Elsewhere?
This issue may be related to this pr https://github.com/dollarshaveclub/reframe.js/pull/88

The issue can be easily replicated by simply removing the width and height attributes from the iframe in the codepen demo https://codepen.io/jakob-maudience/pen/oNNgzQd

**Comment by yowainwright** [comment]
@Jakob-Maudience I'll look into this. Thanks for letting us know.

**Comment by thomasledoux1** [comment]
Hi,

I'm currently using the latest version on NPM to run Reframe, and I am still running into this issue.
I'm importing the module with : 
import reframe from 'reframe.js';

And I then run reframe as follows: 
const iframe = document.querySelector('.video--responsive iframe');

This throws the error @Jakob-Maudience mentioned above.
Version in package.json:

"reframe.js": "^2.2.6",

**Comment by thomasledoux1** [comment]
When I do add height and width to the element, the element does not get the required width & height. The element is not visible at all.
When I add 'padding-top: 50%' to the '.js-frame' class in my CSS it is shown as expected.

**Comment by yowainwright** [comment]
@thomasledoux1 please provide a codepen or examples. ~Thanks for letting me know. 😄

**Comment by yowainwright** [comment]
@thomasledoux1 thank you! You're right. I'll fix it.
