### ISSUE TITLE
Create orphan gh-pages branch and remove landing page from master

### ISSUE THREAD

**Issue by briangonzalez** [dollarshaveclub/reframe.js#6]
As it stands now, since there's no `.npmignore` in this project, you'll ship your landing page to all users running `npm install`.

What do you think about moving all landing stuff to an orphan branch and not committing it to master?

**Comment by jakiestfu** [comment]
The new procedure is adding a `docs` folder which GitHub will sync to github-pages

**Comment by yowainwright** [comment]
Thanks @briangonzalez! Files that aren't part of the package or irrelevant to understanding the package (aka - the gh page) are removed. The gh page, meanwhile is on an orphaned branch & is packaged up for itself. @jakiestfu, thanks for the note. What do you think about creating a `.npmignore` for a `/docs/` folder?
