### ISSUE TITLE
Is calc() necessary in noframe.js?

### ISSUE THREAD

**Issue by tedw** [dollarshaveclub/reframe.js#75]
This script is great! Love the idea of using inline styles to make an iframe responsive instead of wrapping it in a div.

I was just checking out the CodePen demo in Chrome and noticed the inline styles looked like this:

```css
max-height: calc(315px);
height: calc(56.25vw);
```

It seems that Chrome is automatically simplifying the `calc()` formulas, e.g. `calc(560px * 315/560)` was converted to `calc(315px)`.

Seems like it might make sense to do this calculation in the JS and omit `calc()` for simplicity’s sake but wanted to run it by you before submitting a PR.

Thanks!

**Comment by yowainwright** [comment]
@tedw thanks for your thoughtful response! It looks like you might be right. 😊 

Would you mind doing some browser testing with your Pull Request?

Thanks again!

**Comment by yowainwright** [comment]
@tedw do you want to work on this? 😃 ...Or, shall I take it quick?

Thanks again!

**Comment by yowainwright** [comment]
@tedw thanks again for your note! I removed `calc` where possible. 🙏

**Comment by tedw** [comment]
Hey, sorry! Work got busy for me right after I created this issue and I’m afraid it slipped my mind. Thanks for going ahead and making the update 👍
