### ISSUE TITLE
noframe.es.js is actually UMD

### ISSUE THREAD

**Issue by tedw** [dollarshaveclub/reframe.js#99]
I think I found a minor typo in the `build:noframe:es` gulp task:
https://github.com/dollarshaveclub/reframe.js/blob/857710414eb3197d5a60dbb54a981bf93b41018e/gulpfile.js#L109

Seems like this should be `format: 'es'` right?

**Comment by yowainwright** [comment]
@tedw you are right! Do you want to fix that or shall I?

**Comment by tedw** [comment]
feel free! ;)
